name: projeto
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  persistent_bottom_nav_bar: ^5.0.2
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.0.9



  utility_extensions:
    git:
      url: https://github.com/hamzali4642/utility_extensions

  google_maps_flutter: ^2.5.0
  flutter_native_image: ^0.0.6


  fluttertoast: ^8.2.2
  mime: ^1.0.4
  loading_animation_widget: ^1.2.0+4
  provider: ^6.0.5

  #firebase
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  firebase_messaging: ^14.6.5
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.4



  images_picker: ^1.2.11
  file_picker: ^5.5.0
  intl: ^0.18.1
  timeago: ^3.5.0
  timeago_flutter: ^3.5.0
  flutter_credit_card: ^3.0.7


  flutter_background_geolocation: ^4.12.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/